"""initial migration

Revision ID: a846e694b01b
Revises: 
Create Date: 2026-02-17 15:48:19.823749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a846e694b01b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('booking_type_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'completed', 'cancelled', name='booking_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::booking_status_enum"))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('owner_verification', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='owner_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::owner_status_enum"))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'INR'::character varying"))
        batch_op.alter_column('payment_status',
               existing_type=postgresql.ENUM('success', 'failed', 'refunded', name='payment_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'success'::payment_status_enum"))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('space_amenities', schema=None) as batch_op:
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('amenity_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('spaces_pricing', schema=None) as batch_op:
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.create_unique_constraint('unique_space_price_types', ['space_id', 'price_type'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.create_unique_constraint('unique_user_space_wishlist', ['user_id', 'space_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_space_wishlist', type_='unique')
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('spaces_pricing', schema=None) as batch_op:
        batch_op.drop_constraint('unique_space_price_types', type_='unique')
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('space_amenities', schema=None) as batch_op:
        batch_op.alter_column('amenity_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('booking_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=postgresql.ENUM('success', 'failed', 'refunded', name='payment_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'success'::payment_status_enum"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'INR'::character varying"))
        batch_op.alter_column('booking_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('owner_verification', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='owner_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::owner_status_enum"))
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'completed', 'cancelled', name='booking_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::booking_status_enum"))
        batch_op.alter_column('booking_type_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('space_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
